In [1]:
import numpy as np

In [2]:
#creating single dimension array
a=np.array([1,2,3,4,6])

In [3]:
#another one dimension array
b=np.array([22,33,44])

In [4]:
a

array([1, 2, 3, 4, 6])

In [5]:
#creating 2-d array
x=np.array([[2,88],[33,8],[55,9],[33,6]])

In [6]:
x

array([[ 2, 88],
       [33,  8],
       [55,  9],
       [33,  6]])

In [7]:
x[0]  #first row

array([ 2, 88])

In [8]:
x[0][1]  #first row second col

88

In [9]:
#range of row
x[0:2]

array([[ 2, 88],
       [33,  8]])

In [10]:
x+3


array([[ 5, 91],
       [36, 11],
       [58, 12],
       [36,  9]])

In [11]:
x


array([[ 2, 88],
       [33,  8],
       [55,  9],
       [33,  6]])

In [12]:
#dimension
x.shape

(4, 2)

In [13]:
x.reshape(2,4)

array([[ 2, 88, 33,  8],
       [55,  9, 33,  6]])

In [14]:
x

array([[ 2, 88],
       [33,  8],
       [55,  9],
       [33,  6]])

In [15]:
y=x


In [16]:
y

array([[ 2, 88],
       [33,  8],
       [55,  9],
       [33,  6]])

In [17]:
y=x.reshape(2,4)

In [18]:
y

array([[ 2, 88, 33,  8],
       [55,  9, 33,  6]])

In [21]:
#only columns
y[0:,1]

array([88,  9])

In [22]:
x[0: ,1]

array([88,  8,  9,  6])

In [23]:
x

array([[ 2, 88],
       [33,  8],
       [55,  9],
       [33,  6]])

In [24]:
y[: ,1:]

array([[88, 33,  8],
       [ 9, 33,  6]])

In [25]:
y

array([[ 2, 88, 33,  8],
       [55,  9, 33,  6]])

In [27]:
z=np.zeros((5,5))

In [28]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones((6,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
np.full((4,6),6)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [31]:
np.ones((4,4),dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [32]:
#maths operation
x

array([[ 2, 88],
       [33,  8],
       [55,  9],
       [33,  6]])

In [35]:
np.add(x,x)

array([[  4, 176],
       [ 66,  16],
       [110,  18],
       [ 66,  12]])

In [36]:
x

array([[ 2, 88],
       [33,  8],
       [55,  9],
       [33,  6]])

In [37]:
x/25

array([[0.08, 3.52],
       [1.32, 0.32],
       [2.2 , 0.36],
       [1.32, 0.24]])

In [38]:
x

array([[ 2, 88],
       [33,  8],
       [55,  9],
       [33,  6]])