In [13]:
from sklearn import tree
#data set loading
from sklearn import datasets

In [14]:
#finding iris only is very old
for i in dir(datasets):
    if 'iris' in i:   # 'can' for cancer , 'dia' for diabetes
        print(i)

load_iris


In [15]:
#another way of finding datasets
#data=[i for i in dir(datasets)  if 'iris' in i]  # no indentation required (benefit : can use variable for code)

In [16]:
data

['load_iris']

In [17]:
# now exploring iris
dir(data)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [18]:
#explore
iris=datasets.load_iris()
# inside data
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [19]:
#OR
#from sklearn.datasets import load_iris

In [20]:
iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [21]:
iris.feature_names


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [22]:
feature_attribute=iris.feature_names
feature_attribute

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [23]:
#actual data with 4 column and 150 rows , 50 of each flower
features=iris.data
features
features.shape # for counting data

(150, 4)

In [24]:
# to check the type
type(features)

numpy.ndarray

In [25]:
# actual answer 
label=iris.target

In [26]:
iris.target.shape

(150,)

In [27]:
#features[0:50]
label[0:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [28]:
sl=features[:,0] #sepal length - first col
sw=features[:,1] # sepal width = sec col
pl=features[:,2]
pw=features[:,3]

sl.shape

(150,)

In [29]:
# plotting data with matplotlib
import matplotlib.pyplot as plt
plt.scatter(sl,sw,label='SWL')
plt.scatter(sl,pl,label='spl')
plt.scatter(sl,pw,label='slpw')
plt.scatter(pl,pw,label='plpw')
plt.legend()
plt.show()   #or use %matplotlib inlinet

<Figure size 640x480 with 1 Axes>

In [30]:
# now time for dividing data
from sklearn.model_selection import train_test_split
data_split=train_test_split(features,label)
data_split=train_test_split(features,label,test_size=0.2)  #20% data for training

In [31]:
#train_x,test_x,train_y,test=data_split
train_features,test_features,train_label,test_label=data_split  #this is rANDOM SELECTION OF DATA SO IT CAN VARY
#train Q      , test Ques    ,train Ans  ,test Ans

In [32]:
# call classifier
from sklearn import tree
clf=tree.DecisionTreeClassifier()

In [33]:
# now training data
trained=clf.fit(train_features,train_label)

In [34]:
# now prediction 
predicted=trained.predict(test_features)
predicted

array([2, 0, 2, 1, 2, 2, 2, 1, 0, 2, 2, 2, 2, 1, 0, 1, 1, 2, 0, 0, 0, 1,
       1, 0, 2, 1, 2, 1, 2, 1])

In [35]:
#shift+tab    for description  or help
# help(train_test_split)

In [36]:
test_label #actual answer

array([2, 0, 2, 1, 2, 2, 2, 1, 0, 2, 2, 2, 2, 2, 0, 1, 1, 2, 0, 0, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 1])

In [ ]:
#to check accuracy
from sklearn.metrics import accuracy_score
accuracy_score(test_label,predicted)

# iris final

In [ ]:
#about data
#iris.DESCR
#actual ouptut
#iris.target_names #actual target names
#training data is always attribute of target
#iris.feature_name  #attribute of flower
#training data is attribute
features=iris.data #this is complete training data
features.shape #rows(repeatition of same attribute data), columns(will be number of attributes)
'''
Number of Question == Number of Answer #for training of any classifier
'''
label=iris.target
label.shape
#best way to detect label data is to match features and labels --rows

In [ ]:
train_data,test_data,train_ans,test_ans=train_test_split(features,label,test_size=0.2) # by default testing
#we are cutting 20% for testinng data

In [ ]:
#cross checking
train_data.shape

In [38]:
clf=DecitionTreeClassifier()
learn=clf.fit(train_data,train_ans) #here we pass Q and A

NameError: name 'DecitionTreeClassifier' is not defined